suites:
  - trèfle
  - Careau
  - Coeur
  - pique

rank:
  - As
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - Valet
  - Reine
  - Roi

major:
  - Joker (Noir et Blanc)
  - Joker (Couleur)